
GET http://localhost:3000/photos

GET http://localhost:3000/photos/1

GET http://localhost:3000/photos/5

POST http://localhost:3000/photos
Content-Type: application/json
{
  "title": "Утренний кофе",
  "imageUrl": "https://example.com/photos/coffee-morning.jpg",
  "filter": "warm",
  "album": "Повседневность",
  "likes": 5
}

PUT http://localhost:3000/photos/1
Content-Type: application/json
{
  "title": "Закат на море (обновлённый)",
  "imageUrl": "https://example.com/photos/sunset-new.jpg",
  "filter": "sepia",
  "album": "Путешествия",
  "likes": 55
}

DELETE http://localhost:3000/photos/2